
import { ColorPalette } from '../../types';

export const getDesignSystem = (palette: ColorPalette) => {
  switch (palette) {
    case 'modern-blue': 
      return {
        bg: 'bg-slate-50',
        heroGradient: 'bg-gradient-to-br from-slate-900 via-[#0f172a] to-blue-900',
        heroText: 'text-white',
        accentText: 'text-blue-400',
        primaryBtn: 'bg-blue-600 hover:bg-blue-500 shadow-lg shadow-blue-500/30 text-white',
        secondaryBtn: 'bg-white/10 backdrop-blur-sm border border-white/20 text-white hover:bg-white/20',
        cardBg: 'bg-white border border-slate-100 shadow-xl shadow-slate-200/50',
        iconBg: 'bg-blue-100 text-blue-600',
        blobColor: 'bg-blue-500',
        navStickyBg: 'bg-white/95 backdrop-blur-md shadow-xl shadow-blue-900/10 border-b border-gray-100',
        navStickyText: 'text-blue-900',
        logoBg: 'bg-blue-600 text-white',
        introBg: 'bg-[#0B1120]', 
        testimonialBg: 'bg-[#0f172a]', 
        mentorBg: 'bg-[#1e293b]', 
        iconGradient: 'from-blue-500 to-blue-700',
        stepsBg: 'bg-blue-50/50',
        stepGradient: 'from-blue-500 to-blue-700',
        faqBg: 'bg-white',
        faqItemBg: 'bg-slate-50',
        textColor: 'text-blue-600'
      };
    case 'elegant-purple': 
      return {
        bg: 'bg-[#FDFBFF]',
        heroGradient: 'bg-[#1a0b2e]',
        heroText: 'text-white',
        accentText: 'text-purple-400',
        primaryBtn: 'bg-gradient-to-r from-purple-600 to-pink-600 hover:shadow-pink-500/30 shadow-lg text-white',
        secondaryBtn: 'bg-white text-purple-900 hover:bg-gray-100',
        cardBg: 'bg-white border border-purple-50 shadow-lg shadow-purple-100/50',
        iconBg: 'bg-purple-100 text-purple-600',
        blobColor: 'bg-purple-500',
        navStickyBg: 'bg-white/95 backdrop-blur-md shadow-xl shadow-purple-900/10 border-b border-purple-50',
        navStickyText: 'text-purple-900',
        logoBg: 'bg-purple-600 text-white',
        introBg: 'bg-[#2e1065]', 
        testimonialBg: 'bg-[#3b0764]', 
        mentorBg: 'bg-[#4c1d95]', 
        iconGradient: 'from-fuchsia-500 to-fuchsia-700',
        stepsBg: 'bg-purple-50',
        stepGradient: 'from-purple-500 to-pink-500',
        faqBg: 'bg-purple-50/30',
        faqItemBg: 'bg-white',
        textColor: 'text-purple-600'
      };
    case 'energetic-orange': 
      return {
        bg: 'bg-white', 
        heroGradient: 'bg-gradient-to-br from-[#fff7ed] via-[#ffedd5] to-[#fed7aa]',
        heroText: 'text-gray-900',
        accentText: 'text-orange-600',
        primaryBtn: 'bg-gradient-to-r from-orange-600 to-amber-600 hover:from-orange-700 hover:to-amber-700 text-white shadow-lg shadow-orange-500/30 border-t border-white/20',
        secondaryBtn: 'bg-white border border-orange-200 text-orange-800 hover:bg-orange-50',
        cardBg: 'bg-white border border-orange-100 shadow-xl shadow-orange-900/5', 
        iconBg: 'bg-orange-50 text-orange-600',
        blobColor: 'bg-orange-200',
        navStickyBg: 'bg-white/95 backdrop-blur-md shadow-lg shadow-orange-900/5 border-b border-orange-50',
        navStickyText: 'text-gray-900',
        logoBg: 'bg-gradient-to-br from-orange-500 to-amber-500 text-white shadow-orange-500/50',
        introBg: 'bg-[#1c1917]', 
        testimonialBg: 'bg-[#fff7ed]', 
        mentorBg: 'bg-[#1c1917]', 
        iconGradient: 'from-orange-500 to-amber-500',
        stepsBg: 'bg-white',
        stepGradient: 'from-orange-500 to-amber-500',
        faqBg: 'bg-[#fff7ed]',
        faqItemBg: 'bg-white border border-orange-100',
        textColor: 'text-orange-900'
      };
    case 'nature-green': 
      return {
        bg: 'bg-stone-50',
        heroGradient: 'bg-[#1c1917]',
        heroText: 'text-stone-100',
        accentText: 'text-green-400',
        primaryBtn: 'bg-green-600 hover:bg-green-500 text-white shadow-lg shadow-green-900/20',
        secondaryBtn: 'border border-stone-600 text-stone-300 hover:text-white',
        cardBg: 'bg-[#fafaf9] border border-stone-200 shadow-sm',
        iconBg: 'bg-green-100 text-green-700',
        blobColor: 'bg-green-500',
        navStickyBg: 'bg-white/95 backdrop-blur-md shadow-xl shadow-green-900/10 border-b border-stone-100',
        navStickyText: 'text-stone-800',
        logoBg: 'bg-green-600 text-white',
        introBg: 'bg-[#064e3b]', 
        testimonialBg: 'bg-[#022c22]',
        mentorBg: 'bg-[#052e16]',
        iconGradient: 'from-green-500 to-emerald-700',
        stepsBg: 'bg-stone-100',
        stepGradient: 'from-green-500 to-emerald-600',
        faqBg: 'bg-stone-100',
        faqItemBg: 'bg-white',
        textColor: 'text-green-700'
      };
    case 'dark-luxury': 
      return {
        bg: 'bg-[#0a0a0a]',
        heroGradient: 'bg-black',
        heroText: 'text-white',
        accentText: 'text-yellow-500',
        primaryBtn: 'bg-gradient-to-r from-yellow-600 to-yellow-500 hover:from-yellow-500 hover:to-yellow-400 text-black font-bold shadow-lg shadow-yellow-500/20',
        secondaryBtn: 'border border-yellow-900/50 text-yellow-500 hover:bg-yellow-900/10',
        cardBg: 'bg-[#111] border border-[#222] shadow-2xl',
        iconBg: 'bg-yellow-900/20 text-yellow-500',
        blobColor: 'bg-yellow-600',
        navStickyBg: 'bg-white/95 backdrop-blur-md shadow-xl shadow-black/20 border-b border-gray-200',
        navStickyText: 'text-black',
        logoBg: 'bg-yellow-500 text-black',
        introBg: 'bg-[#111111]',
        testimonialBg: 'bg-black',
        mentorBg: 'bg-[#1c1917]',
        iconGradient: 'from-yellow-600 to-yellow-800',
        stepsBg: 'bg-[#111]',
        stepGradient: 'from-yellow-600 to-amber-700',
        faqBg: 'bg-[#0a0a0a]',
        faqItemBg: 'bg-[#111]',
        textColor: 'text-yellow-600'
      };
    case 'ocean-teal': 
      return {
        bg: 'bg-cyan-50/30',
        heroGradient: 'bg-gradient-to-br from-cyan-900 to-teal-900',
        heroText: 'text-white',
        accentText: 'text-cyan-300',
        primaryBtn: 'bg-cyan-400 hover:bg-cyan-300 text-cyan-950 font-bold shadow-lg shadow-cyan-400/20',
        secondaryBtn: 'border border-cyan-700 text-cyan-100',
        cardBg: 'bg-white border border-cyan-100 shadow-lg shadow-cyan-100',
        iconBg: 'bg-cyan-100 text-cyan-600',
        blobColor: 'bg-cyan-400',
        navStickyBg: 'bg-white/95 backdrop-blur-md shadow-xl shadow-cyan-900/10 border-b border-cyan-50',
        navStickyText: 'text-cyan-900',
        logoBg: 'bg-cyan-400 text-cyan-950',
        introBg: 'bg-[#0e7490]', 
        testimonialBg: 'bg-[#164e63]',
        mentorBg: 'bg-[#083344]',
        iconGradient: 'from-cyan-500 to-teal-600',
        stepsBg: 'bg-cyan-50',
        stepGradient: 'from-cyan-400 to-teal-500',
        faqBg: 'bg-cyan-50/50',
        faqItemBg: 'bg-white',
        textColor: 'text-cyan-700'
      };
    case 'crimson-red': 
      return {
        bg: 'bg-white',
        heroGradient: 'bg-[#881337]',
        heroText: 'text-white',
        accentText: 'text-rose-200',
        primaryBtn: 'bg-white text-[#881337] font-bold hover:bg-rose-50 shadow-xl',
        secondaryBtn: 'bg-rose-900 border border-rose-700 text-rose-200',
        cardBg: 'bg-white border border-rose-100 shadow-xl shadow-rose-100',
        iconBg: 'bg-rose-100 text-rose-700',
        blobColor: 'bg-rose-500',
        navStickyBg: 'bg-white/95 backdrop-blur-md shadow-xl shadow-rose-900/10 border-b border-rose-50',
        navStickyText: 'text-rose-900',
        logoBg: 'bg-rose-600 text-white',
        introBg: 'bg-[#881337]',
        testimonialBg: 'bg-[#4c0519]',
        mentorBg: 'bg-[#9f1239]',
        iconGradient: 'from-red-600 to-rose-700',
        stepsBg: 'bg-rose-50',
        stepGradient: 'from-red-500 to-rose-600',
        faqBg: 'bg-rose-50/30',
        faqItemBg: 'bg-white',
        textColor: 'text-rose-700'
      };
    case 'corporate-slate': 
      return {
        bg: 'bg-slate-50',
        heroGradient: 'bg-slate-800',
        heroText: 'text-white',
        accentText: 'text-slate-300',
        primaryBtn: 'bg-slate-700 hover:bg-slate-600 text-white shadow-lg',
        secondaryBtn: 'bg-transparent border border-white/20 text-white',
        cardBg: 'bg-white border border-slate-200 shadow-md',
        iconBg: 'bg-slate-100 text-slate-700',
        blobColor: 'bg-slate-400',
        navStickyBg: 'bg-white/95 backdrop-blur-md shadow-xl shadow-slate-900/10 border-b border-slate-100',
        navStickyText: 'text-slate-800',
        logoBg: 'bg-slate-700 text-white',
        introBg: 'bg-[#334155]',
        testimonialBg: 'bg-[#020617]',
        mentorBg: 'bg-[#1e293b]',
        iconGradient: 'from-slate-600 to-slate-800',
        stepsBg: 'bg-slate-100',
        stepGradient: 'from-slate-600 to-slate-800',
        faqBg: 'bg-slate-100',
        faqItemBg: 'bg-white',
        textColor: 'text-slate-700'
      };
    case 'gold-prestige': 
      return {
        bg: 'bg-[#fffcf5]',
        heroGradient: 'bg-gradient-to-r from-yellow-700 to-yellow-600',
        heroText: 'text-white',
        accentText: 'text-yellow-200',
        primaryBtn: 'bg-yellow-600 hover:bg-yellow-500 text-white shadow-lg',
        secondaryBtn: 'bg-transparent border border-white/20 text-white',
        cardBg: 'bg-white border border-yellow-100 shadow-lg',
        iconBg: 'bg-yellow-50 text-yellow-600',
        blobColor: 'bg-yellow-500',
        navStickyBg: 'bg-white/95 backdrop-blur-md shadow-xl shadow-yellow-900/10 border-b border-yellow-50',
        navStickyText: 'text-yellow-900',
        logoBg: 'bg-yellow-600 text-white',
        introBg: 'bg-[#422006]',
        testimonialBg: 'bg-[#1c1917]',
        mentorBg: 'bg-[#451a03]',
        iconGradient: 'from-yellow-600 to-amber-700',
        stepsBg: 'bg-yellow-50',
        stepGradient: 'from-yellow-500 to-amber-600',
        faqBg: 'bg-orange-50/20',
        faqItemBg: 'bg-white',
        textColor: 'text-yellow-700'
      };
    case 'minimal-mono': 
      return {
        bg: 'bg-white',
        heroGradient: 'bg-white',
        heroText: 'text-black',
        accentText: 'text-gray-500',
        primaryBtn: 'bg-black text-white hover:bg-gray-800 shadow-lg',
        secondaryBtn: 'border border-gray-300 text-gray-600 hover:border-black hover:text-black',
        cardBg: 'bg-white border border-gray-200 shadow-sm hover:shadow-md',
        iconBg: 'bg-gray-100 text-black',
        blobColor: 'bg-gray-300',
        navStickyBg: 'bg-white/95 backdrop-blur-md shadow-xl shadow-black/10 border-b border-gray-100',
        navStickyText: 'text-black',
        logoBg: 'bg-black text-white',
        introBg: 'bg-black',
        testimonialBg: 'bg-black',
        mentorBg: 'bg-black',
        iconGradient: 'from-gray-700 to-black',
        stepsBg: 'bg-gray-50',
        stepGradient: 'from-gray-800 to-black',
        faqBg: 'bg-gray-50',
        faqItemBg: 'bg-white',
        textColor: 'text-gray-900'
      };
    default: 
       return {
        bg: 'bg-slate-50',
        heroGradient: 'bg-gradient-to-br from-slate-900 via-[#0f172a] to-blue-900',
        heroText: 'text-white',
        accentText: 'text-blue-400',
        primaryBtn: 'bg-blue-600 hover:bg-blue-500 shadow-lg shadow-blue-500/30 text-white',
        secondaryBtn: 'bg-white/10 backdrop-blur-sm border border-white/20 text-white hover:bg-white/20',
        cardBg: 'bg-white border border-slate-100 shadow-xl shadow-slate-200/50',
        iconBg: 'bg-blue-100 text-blue-600',
        blobColor: 'bg-blue-500',
        navStickyBg: 'bg-white/95 backdrop-blur-md shadow-xl shadow-blue-900/10 border-b border-gray-100',
        navStickyText: 'text-blue-900',
        logoBg: 'bg-blue-600 text-white',
        introBg: 'bg-[#0B1120]',
        testimonialBg: 'bg-[#0f172a]',
        mentorBg: 'bg-[#1e293b]',
        iconGradient: 'from-blue-500 to-blue-700',
        stepsBg: 'bg-blue-50/50',
        stepGradient: 'from-blue-500 to-blue-700',
        faqBg: 'bg-white',
        faqItemBg: 'bg-slate-50',
        textColor: 'text-blue-600'
      };
  }
};
