steps:
  # 1) Build de la imagen
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "europe-southwest1-docker.pkg.dev/$PROJECT_ID/plataformadeventacom/plataformadeventacom:$SHORT_SHA"
      - "."

  # 2) Push a Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "europe-southwest1-docker.pkg.dev/$PROJECT_ID/plataformadeventacom/plataformadeventacom:$SHORT_SHA"

  # 3) Deploy a Cloud Run en europe-west1 (OJO: región cambiada)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    /* */ /* Actualización: Se añade el parámetro --timeout para prevenir errores de despliegue por arranque lento y se mantiene la configuración de Cloud SQL - 15/06/2024 10:45 */
    args:
      - "run"
      - "deploy"
      - "plataformadeventacom"   # mismo nombre de servicio
      - "--image"
      - "europe-southwest1-docker.pkg.dev/$PROJECT_ID/plataformadeventacom/plataformadeventacom:$SHORT_SHA"
      - "--region"
      - "europe-west1"           # <- ANTES era europe-southwest1
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--timeout"
      - "600"
      - "--add-cloudsql-instances"
      - "gen-lang-client-0436624801:europe-southwest1:plataformadeventacom-sql"

images:
  - "europe-southwest1-docker.pkg.dev/$PROJECT_ID/plataformadeventacom/plataformadeventacom:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY